project:
  type: website
  output-dir: docs

website:
  title: "Bailey Jørgensen"
  favicon: images/lineguy.png
  navbar:
    title: BAILEY JØRGENSEN, MSc
    #logo: #file path for logo in images folder
    #logo-alt: "my alt text"
    right:
      - href: index.qmd
        text: PORTFOLIO
      - href: about.qmd
        text: About
     # - href: resources.qmd
     #   text: Resources
      - href: cv.qmd
        text: Resume
     # - href: contact.qmd
      - text: Contact
        menu:
          - text: LinkedIn
            icon: linkedin
            href: https://www.linkedin.com/in/bailey-j%C3%B8rgensen-a0a467271/
            target: _blank
          - text: Email
            icon: envelope
            href: mailto:bjorgensen@alfmuseum.org
            target: _blank

  page-footer:
    background: dark
    left: '{{< fa copyright >}} 2025, Bailey Jørgensen'
    right: This website is built with {{< fa brands github title="The GitHub octocat logo" >}}


format:
  html:
    theme: styles.scss
    css: styles.css
    mainfont: Roboto
    fontcolor: "#FFFFFF"
    toc: false
    page-layout: full


